# ============================================================================ #
# Author: Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
from docker.io/debian:12.15
copy ./fs/root/setup.sh /root/setup.sh
run \
  /bin/bash -x /root/setup.sh ; \
  rm -f /root/setup.sh
entrypoint ["/bin/bash"]
cmd ["/root/entrypoint.sh"]
# ============================================================================ #
