# ============================================================================ #
# Author: Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
from docker.io/alpine:3.24.1
copy ./fs/root/setup.sh /root/setup.sh
run \
  /bin/bash /root/setup.sh ; \
  rm -f /root/setup.sh
entrypoint ["/bin/bash"]
cmd ["/root/entrypoint.sh"]
# ============================================================================ #
