# ============================================================================ #
name: Build and Push Images

on:
  push:
    branches:
    - main
    paths:
    - 'images/pg-dhcp/**'
    - 'images/openvpn-client/**'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          pg-dhcp:
          - 'images/pg-dhcp/**'
          openvpn-client:
          - 'images/openvpn-client/**'

  build:
    needs: filter
    if: ${{ needs.filter.outputs.changes != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.filter.outputs.changes) }}
    steps:
    - uses: actions/checkout@v4
    - name: Debug Workspace
      run: |
        echo "Current directory: $(pwd)"
        # This will list all files recursively
        ls -R
        ls -la ./images/${{ matrix.folder }}/build_context
        ls -la ./images/${{ matrix.folder }}/Containerfile
        cat ./images/${{ matrix.folder }}/Containerfile
    - name: Build image with Buildah
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/paul-grozav/${{ matrix.folder }}
        tags: latest ${{ github.sha }}
        context: ./images/${{ matrix.folder }}/build_context
        dockerfiles: ./images/${{ matrix.folder }}/Containerfile
    - name: Push to Registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ghcr.io/paul-grozav/${{ matrix.folder }}
        tags: latest ${{ github.sha }}
        registry: ghcr.io/paul-grozav
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
# ============================================================================ #
